### ISSUE TITLE
Automating online documentation (proposal)

### ISSUE THREAD

**Issue by acrlakshman** [9prady9/MeshIO#37]
@9prady9 

* I thought to create a project for this. Here is the purpose of creating this issue (not exactly an issue).
    * I think we can add documentation while we are coding and when we push it, build bot can automatically generate documentation and push it to github pages
    * I saw this from https://github.com/OrionQuest/Nova. It looks pretty good. What do you think?

**Comment by 9prady9** [comment]
Do we really want to update documentation on gh-pages for every new commit ? It may make sense now since we don't have any versions or releases what so ever, but once we have versioning and releases it won't be a helpful. Unless, we can version the documentation as well. Even then, we wouldn't want to push doc updates for each commit hash, docs update for release tags only makes sense.

Given that, lets start versioning from now itself. lets start with `0.1.0` - may be when we had working STL read and write functions. It's fine even if we have bugs in it. Once we merge OBJ read/write functions, lets do `0.2.0`. Let's keep the branch workflow simple, we use master as main branch until we do a `1.0.0` release at which point, we will create `devel` & `hotfixes-1.0.x` pointing to master's `1.0.0` tag. We will use the workflow mentioned [here](http://nvie.com/posts/a-successful-git-branching-model/).

**Comment by 9prady9** [comment]
Let's put both STL and OBJ in 0.1.0, I was just illustrating with an example. Closing this issue now. Lets just push docs with releases - it hardly takes few minutes to do it. I have a script that does this automatically, lets avoid unnecessary complexity.
